In [64]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [73]:
# import dataset
dataset = pd.read_csv('DataMining.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [74]:
# Splitting dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [75]:
dataset

Nama  Umur  RestingBP  Cholestrol  FastingBS  MaxHR  Oldpeak HeartDisease
0  Dina    23      140.0         289          0    172      0.0           No
1  Dodi    49      160.0         180          0    156      1.0          Yes
2  Didi    49        NaN         180          0    156      NaN          Yes
3  Dodi    49      160.0         180          0    156      1.0          Yes
4  Dodi    49      160.0         180          0    156      1.0          Yes
5  Dodi    49      160.0         180          0    156      1.0          Yes
6  Dodi    49      160.0         180          0    156      1.0          Yes
7  Dodi    49      160.0         180          0    156      1.0          Yes
8  Dodi    49      160.0         180          0    156      1.0          Yes

In [76]:
print(x)

[['Dina' 23 140.0 289 0 172 0.0]
 ['Dodi' 49 160.0 180 0 156 1.0]
 ['Didi' 49 nan 180 0 156 nan]
 ['Dodi' 49 160.0 180 0 156 1.0]
 ['Dodi' 49 160.0 180 0 156 1.0]
 ['Dodi' 49 160.0 180 0 156 1.0]
 ['Dodi' 49 160.0 180 0 156 1.0]
 ['Dodi' 49 160.0 180 0 156 1.0]
 ['Dodi' 49 160.0 180 0 156 1.0]]


In [77]:
print(y)

['No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes']


In [78]:
# Menghilangkan Missing Value (nan)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [79]:
# Encoding data kategori (Atribut)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [80]:
print(x)

[[0.0 1.0 0.0 23.0 140.0 289 0 172 0.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [1.0 0.0 0.0 49.0 157.5 180 0 156 nan]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]]


In [81]:
# Encoding data kategori (class/label)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [82]:
print(y)

[0 1 1 1 1 1 1 1 1]


In [83]:
# Membagi dataset ke dalam training set dan test set
# Splitting dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print(x_train)


[[0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 1.0 0.0 23.0 140.0 289 0 172 0.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]]


In [84]:
print(x_test)

[[0.0 0.0 1.0 49.0 160.0 180 0 156 1.0]
 [1.0 0.0 0.0 49.0 157.5 180 0 156 nan]]


In [85]:
print(y_train)


[1 1 1 0 1 1 1]


In [86]:
print(y_test)

[1 1]
