In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# import dataset
dataset = pd.read_csv('DataMining.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
# Splitting dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [4]:
dataset

Nama  Umur  RestingBP  Cholestrol  FastingBS  MaxHR  Oldpeak HeartDisease
0  Dina  23.0      140.0       289.0          0    172      0.0           No
1  Dodi  49.0      160.0       180.0          0    156      1.0          Yes
2  Didi  49.0        NaN       180.0          0    156      NaN          Yes
3  Nina  20.0      150.0       130.0          1    165      0.0           No
4  Nino   NaN      170.0       180.0          0    150      1.0          Yes
5  Dika  25.0        NaN       185.0          1     90      0.0           No
6  Kika  43.0      160.0         NaN          0   1709      0.0           No

In [5]:
print(x)

[['Dina' 23.0 140.0 289.0 0 172 0.0]
 ['Dodi' 49.0 160.0 180.0 0 156 1.0]
 ['Didi' 49.0 nan 180.0 0 156 nan]
 ['Nina' 20.0 150.0 130.0 1 165 0.0]
 ['Nino' nan 170.0 180.0 0 150 1.0]
 ['Dika' 25.0 nan 185.0 1 90 0.0]
 ['Kika' 43.0 160.0 nan 0 1709 0.0]]


In [6]:
print(y)

['No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No']


In [7]:
# Menghilangkan Missing Value (nan)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [8]:
# Encoding data kategori (Atribut)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [9]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 23.0 140.0 289.0 0 172 0.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 49.0 160.0 180.0 0 156 1.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 49.0 156.0 180.0 0 156 nan]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 20.0 150.0 130.0 1 165 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 34.833333333333336 170.0 180.0 0 150 1.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 25.0 156.0 185.0 1 90 0.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 43.0 160.0 nan 0 1709 0.0]]


In [10]:
# Encoding data kategori (class/label)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 1 0 1 0 0]


In [12]:
# Membagi dataset ke dalam training set dan test set
# Splitting dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print(x_train)


[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 49.0 160.0 180.0 0 156 1.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 23.0 140.0 289.0 0 172 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 34.833333333333336 170.0 180.0 0 150 1.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 20.0 150.0 130.0 1 165 0.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 25.0 156.0 185.0 1 90 0.0]]


In [13]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 43.0 160.0 nan 0 1709 0.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 49.0 156.0 180.0 0 156 nan]]


In [14]:
print(y_train)


[1 0 1 0 0]


In [15]:
print(y_test)

[0 1]
